#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Mar 07 21:33:23 CET 2026
maven-metadata-papermc.xml.lastUpdated=1772915603604
maven-metadata-placeholderapi.xml.error=
maven-metadata-placeholderapi.xml.lastUpdated=1772915603607
maven-metadata-sk89q-repo.xml.lastUpdated=1772915603606
maven-metadata-spigot-repo.xml.error=
maven-metadata-spigot-repo.xml.lastUpdated=1772915603605
